-- Ejecutar este código en Supabase > SQL Editor

CREATE TABLE IF NOT EXISTS tramites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ciudadano TEXT NOT NULL,
    dni TEXT NOT NULL,
    correo TEXT NOT NULL,
    tipo_tramite TEXT NOT NULL,
    area TEXT NOT NULL,
    descripcion TEXT NOT NULL,
    dias_espera INTEGER NOT NULL,
    urgencia INTEGER NOT NULL,
    documentos_observados INTEGER NOT NULL,
    prioridad TEXT NOT NULL,
    estado TEXT NOT NULL DEFAULT 'Recibido',
    fecha_registro TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS notificaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tramite_id BIGINT NOT NULL REFERENCES tramites(id) ON DELETE CASCADE,
    mensaje TEXT NOT NULL,
    fecha TIMESTAMPTZ DEFAULT NOW()
);

-- Para demo académica puedes dejar RLS desactivado.
-- Si activas RLS, crea políticas según tu necesidad.
ALTER TABLE tramites DISABLE ROW LEVEL SECURITY;
ALTER TABLE notificaciones DISABLE ROW LEVEL SECURITY;
